language: python

python:
  - "2.7"
  - "3.6"

env:
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10

matrix:
  allow_failures:
    - env: DJANGO_VERSION=dev

install:
    - pip install tox

script:
    - tox -e py${TRAVIS_PYTHON_VERSION/./}-${DJANGO_VERSION}
